#------------------------------------------------------------------------------
# $File: varied.script,v 1.17 2025/03/10 20:41:09 christos Exp $
# varied.script:  file(1) magic for various interpreter scripts

# LOCAL(qjerome): upstream's "0 string #![ Rust Source file" dropped
# here. It's a weak, redundant duplicate of the proper Rust source
# detection in magdir/rust.

0	string/wt	#!\ 	a
>&-1	string/T	x	%s script text executable
!:strength / 3

0	string/wb	#!\ 	a
>&-1	string/T	x	%s script executable (binary data)
!:strength / 3


# using env
# LOCAL(qjerome): "1l" added (perf: shebang is always line 1)
0	regex/1lt		#![[:space:]]*/usr/bin/env[[:space:]]*	a
>&0	string/T	>\0			%s script text executable
!:strength / 2

# LOCAL(qjerome): "1l" added (perf: shebang is always line 1)
0	regex/1lb		#![[:space:]]*/usr/bin/env[[:space:]]*	a
>&0	string/T	>\0			%s script executable (binary data)
!:strength / 2

# using env
# LOCAL(qjerome): "1l" added (perf: shebang is always line 1)
0	regex/1lt		#![[:space:]]*/usr/bin/env[[:space:]]*-[Si0]	a
>&0	string/T	>\0			%s script text executable
!:strength / 2

# LOCAL(qjerome): "1l" added (perf: shebang is always line 1)
0	regex/1lb		#![[:space:]]*/usr/bin/env[[:space:]]*-[Si0]	a
>&0	string/T	>\0			%s script executable (binary data)
!:strength / 2
