[package]
name = "magic-db"
version = "0.4.4"
edition.workspace = true
rust-version.workspace = true
description = "This crate provides a precompiled magic database for file type identification. It allows any program to perform magic file detection without the burden of compiling rules from source."
repository.workspace = true
license.workspace = true
keywords = ["database", "embedded", "libmagic", "magic", "mime"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
magic-embed = { path = "../magic-embed", version = "0.3.4" }
pure-magic = { path = "../pure-magic", version = "0.2.4" }

[features]
global = []
