[package]
name = "wiza"
version = "0.3.0"
edition.workspace = true
rust-version.workspace = true
description = "Command line tool for file identification"
repository.workspace = true
license.workspace = true
keywords = ["cli", "file", "identification", "magic", "mime"]

[[bin]]
name = "wiza"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.42", features = ["derive"] }
fs-walk = "0.2.0"
magic-db = { path = "../magic-db", version = "0.5.0" }
pure-magic = { path = "../pure-magic", version = "0.3.0" }
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.145"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
